---
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  lint:
    uses: openconfig/common-ci/.github/workflows/linter.yml@9bd215b60afdefd1633ca8d20101cd03534e19b1
    permissions:
      contents: read
      packages: read
